### ISSUE TITLE
Fellner ft. WAPPIE - Death Style

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Map-Testing#689]
Issue created by: Backflip
  Map reported: Fellner ft. WAPPIE - Death Style
  Issue:  after first dinghy part (so, after inf pickup) and after the jump, a shade is missing; the inf pickup after second dinghy part is very far away and cant be reached, i think it should be moved closer (i think its OS A but i cant test the map further than this part)
  Date: 23/12/2020 01:16:55

**Comment by Relaxz0r** [comment]
the main issue of that map was 0 scripts working (everything was client-sided also lol), was working fine on local server. Then i just decided to delete ENCRYPTED script (because script parts were not working at all and you were basically skipping them) and all of a sudden every missing script started working (textures,trees, music, missing scripts on dinghy parts), i dunno how encrypted files manage to block other scripts but they do it
